build: resolve build errors in dependent programs
The headers do not compile standalone which may cause compilation
problems to third party programs.

	$ gcc -x c -Wall -c *.h
	chain.h:62:35: error: unknown type name ‘size_t’
	expr.h:40:39: error: unknown type name ‘size_t’
	rule.h:60:34: error: unknown type name ‘size_t’
	ruleset.h:20:1: error: unknown type name ‘bool’
	ruleset.h:20:59: error: unknown type name ‘uint16_t’
	ruleset.h:21:52: error: unknown type name ‘uint16_t’
	ruleset.h:22:50: error: unknown type name ‘uint16_t’
	ruleset.h:23:63: error: unknown type name ‘uint16_t’
	ruleset.h:39:37: error: unknown type name ‘size_t’
	ruleset.h:39:80: error: unknown type name ‘uint32_t’
	ruleset.h:39:95: error: unknown type name ‘uint32_t’
	set.h:40:33: error: unknown type name ‘size_t’
	set.h:110:38: error: unknown type name ‘size_t’
	table.h:50:35: error: unknown type name ‘size_t’

Signed-off-by: Jan Engelhardt <jengelh@inai.de>
Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>