expr: log: define variable flags in xml parser
In the xml parser, we have used a variable flags for parsing it
but we have forgot define it. This patch solves a compile error
like:

expr/log.c:263:12: error: 'flags' undeclared (first use in this function)

Signed-off-by: Alvaro Neira Ayuso <alvaroneay@gmail.com>
Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>